module.exports = {
    USER_CONNECTED: "USER_CONNECTED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    TYPING: "TYPING",
    LOGOUT: "LOGOUT",
    PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
    NEW_CHAT: "NEW_CHAT",
    CHAT_STARTED: "CHAT_STARTED"
}